import baseFederation from './federation';

interface Env {
  SUPABASE_URL: string;
  SUPABASE_ANON_KEY: string;
  SUPABASE_SERVICE_ROLE_KEY: string;
  FEDERATION_DOMAIN: string;
  ACTOR_BASE_URL: string;
  FEDERATION_USER_AGENT?: string;
  FEDERATION_KEY_ENCRYPTION_SECRET: string;
}
const AP='application/activity+json';
const PUBLIC='https://www.w3.org/ns/activitystreams#Public';
const enc=(v:string)=>encodeURIComponent(v);
const b64=(u:Uint8Array)=>{let s='';for(const x of u)s+=String.fromCharCode(x);return btoa(s)};
const b64u=(u:Uint8Array)=>b64(u).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const bytes=(s:string)=>{const b=atob(s.replace(/-/g,'+').replace(/_/g,'/'));const u=new Uint8Array(b.length);for(let i=0;i<b.length;i++)u[i]=b.charCodeAt(i);return u};
const json=(x:unknown,status=200)=>new Response(JSON.stringify(x),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}});
function safeRemote(uri:string,env:Env){try{const u=new URL(uri);if(u.protocol!=='https:')return false;const h=u.hostname.toLowerCase();if(h==='localhost'||h.endsWith('.localhost')||h==='0.0.0.0'||h==='127.0.0.1'||h==='::1'||/^10\./.test(h)||/^192\.168\./.test(h)||/^169\.254\./.test(h)||/^172\.(1[6-9]|2\d|3[01])\./.test(h))return false;return h!==new URL(env.ACTOR_BASE_URL).hostname.toLowerCase()||true}catch{return false}}
async function db(env:Env,path:string,method='GET',body?:unknown,prefer?:string){const r=await fetch(env.SUPABASE_URL+path,{method,headers:{apikey:env.SUPABASE_SERVICE_ROLE_KEY,Authorization:`Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,'content-type':'application/json',...(prefer?{Prefer:prefer}:{})},body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok)throw new Error(`Supabase ${r.status}: ${(await r.text()).slice(0,200)}`);const t=await r.text();return t?JSON.parse(t):null;}
async function userId(request:Request,env:Env){const a=request.headers.get('Authorization')||'';if(!a.startsWith('Bearer '))return null;const r=await fetch(env.SUPABASE_URL+'/auth/v1/user',{headers:{apikey:env.SUPABASE_ANON_KEY,Authorization:a}});if(!r.ok)return null;const u=await r.json() as {id?:string};return u.id||null;}
async function derive(secret:string){return crypto.subtle.digest('SHA-256',new TextEncoder().encode(secret));}
async function encrypt(value:string,secret:string){const key=await crypto.subtle.importKey('raw',await derive(secret),{name:'AES-GCM'},false,['encrypt']);const iv=crypto.getRandomValues(new Uint8Array(12));const c=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(value));return {cipher:b64u(new Uint8Array(c)),iv:b64u(iv)};}
async function decrypt(cipher:string,iv:string,secret:string){const key=await crypto.subtle.importKey('raw',await derive(secret),{name:'AES-GCM'},false,['decrypt']);const p=await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes(iv)},key,bytes(cipher));return new TextDecoder().decode(p);}
function pem(data:ArrayBuffer,label:string){return `-----BEGIN ${label}-----\n${b64(new Uint8Array(data)).match(/.{1,64}/g)?.join('\n')}\n-----END ${label}-----`}
async function ensureKey(env:Env,userId:string){const base=env.ACTOR_BASE_URL.replace(/\/$/,'');const profile=await db(env,`/rest/v1/profiles?id=eq.${enc(userId)}&select=username,display_name,bio,avatar_url`);if(!profile?.[0])throw new Error('profile_not_found');const actor=`${base}/users/${enc(profile[0].username)}`;const existing=await db(env,`/rest/v1/federated_actors?uri=eq.${enc(actor)}&select=uri,public_key_id,public_key_pem,private_key_ciphertext,private_key_iv`);if(existing?.[0]?.private_key_ciphertext&&existing?.[0]?.private_key_iv&&existing[0].public_key_pem)return {actor,profile:profile[0],keyId:existing[0].public_key_id,privatePem:await decrypt(existing[0].private_key_ciphertext,existing[0].private_key_iv,env.FEDERATION_KEY_ENCRYPTION_SECRET)};const kp=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);const pub=pem(await crypto.subtle.exportKey('spki',kp.publicKey),'PUBLIC KEY');const priv=pem(await crypto.subtle.exportKey('pkcs8',kp.privateKey),'PRIVATE KEY');const e=await encrypt(priv,env.FEDERATION_KEY_ENCRYPTION_SECRET);const instance=await db(env,`/rest/v1/federated_instances?on_conflict=domain`,{domain:env.FEDERATION_DOMAIN,protocol:'activitypub',status:'active',updated_at:new Date().toISOString() },'POST','resolution=merge-duplicates,return=representation');const instanceId=instance?.[0]?.id||null;const keyId=`${actor}#main-key`;await db(env,'/rest/v1/federated_actors?on_conflict=uri','POST',{instance_id:instanceId,uri:actor,webfinger:`acct:${profile[0].username}@${env.FEDERATION_DOMAIN}`,preferred_username:profile[0].username,display_name:profile[0].display_name||profile[0].username,summary:profile[0].bio||'',avatar_url:profile[0].avatar_url||null,public_key_id:keyId,public_key_pem:pub,private_key_ciphertext:e.cipher,private_key_iv:e.iv,fetched_at:new Date().toISOString(),updated_at:new Date().toISOString()},'resolution=merge-duplicates');return {actor,profile:profile[0],keyId,privatePem:priv};}
async function signAndPost(env:Env,actor:string,keyId:string,privatePem:string,inbox:string,activity:unknown){const body=JSON.stringify(activity);const url=new URL(inbox);const date=new Date().toUTCString();const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(body));const digest='SHA-256='+b64(new Uint8Array(hash));const signing=`(request-target): post ${url.pathname}${url.search}\nhost: ${url.host}\ndate: ${date}\ndigest: ${digest}`;const clean=privatePem.replace(/-----BEGIN PRIVATE KEY-----|-----END PRIVATE KEY-----|\s/g,'');const key=await crypto.subtle.importKey('pkcs8',bytes(clean),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);const sig=b64(new Uint8Array(await crypto.subtle.sign({name:'RSASSA-PKCS1-v1_5'},key,new TextEncoder().encode(signing))));const r=await fetch(inbox,{method:'POST',headers:{'content-type':AP,accept:AP,date,digest,signature:`keyId="${keyId}",headers="(request-target) host date digest",signature="${sig}"`,'user-agent':env.FEDERATION_USER_AGENT||'TV49-East-Federation/1.0'},body});return r;}
async function remoteActor(uri:string,env:Env){if(!safeRemote(uri,env))throw new Error('unsafe_remote');const r=await fetch(uri,{headers:{accept:`${AP}, application/ld+json; profile="https://www.w3.org/ns/activitystreams"`,'user-agent':env.FEDERATION_USER_AGENT||'TV49-East-Federation/1.0'},redirect:'manual'});if(!r.ok)throw new Error(`remote_actor_${r.status}`);const a=await r.json() as any;if(typeof a.id!=='string'||new URL(a.id).hostname.toLowerCase()!==new URL(uri).hostname.toLowerCase())throw new Error('actor_identity_mismatch');return a;}
async function action(request:Request,env:Env){const uid=await userId(request,env);if(!uid)return json({error:'unauthorized'},401);let b:any;try{b=await request.json()}catch{return json({error:'invalid_json'},400)}const type=String(b.action||'');const target=String(b.target_uri||'');const objectUri=String(b.object_uri||'');if(!['follow','unfollow','like','unlike','repost','unrepost'].includes(type)||!/^https:\/\//i.test(target||objectUri))return json({error:'invalid_action'},400);const local=await ensureKey(env,uid);let targetActorUri=target;let remote:any;if(type.includes('follow')) remote=await remoteActor(target,env);else {const obj=await db(env,`/rest/v1/federated_objects?uri=eq.${enc(objectUri)}&select=uri,actor_uri`);targetActorUri=obj?.[0]?.actor_uri;if(!targetActorUri)throw new Error('remote_object_actor_missing');remote=await remoteActor(targetActorUri,env)}const inbox=remote?.endpoints?.sharedInbox||remote?.inbox;if(!inbox||!safeRemote(inbox,env))throw new Error('remote_inbox_missing');const id=`${local.actor}/activities/${crypto.randomUUID()}`;let activity:any;if(type==='follow'||type==='unfollow'){const follow={id,type:'Follow',actor:local.actor,object:targetActorUri,to:[targetActorUri]};activity=type==='follow'?follow:{'@context':'https://www.w3.org/ns/activitystreams',id,type:'Undo',actor:local.actor,object:follow,to:[targetActorUri]};}else{const base={id,type:type==='like'||type==='unlike'?'Like':'Announce',actor:local.actor,object:objectUri,to:[targetActorUri]};activity=type==='like'||type==='repost'?base:{'@context':'https://www.w3.org/ns/activitystreams',id,type:'Undo',actor:local.actor,object:base,to:[targetActorUri]};}
await db(env,'/rest/v1/federated_activities?on_conflict=uri','POST',{uri:id,activity_type:activity.type,actor_uri:local.actor,object_uri:typeof activity.object==='string'?activity.object:(activity.object?.id||objectUri),instance_id:null,direction:'outbound',local_user_id:uid,raw_activity:activity,received_at:new Date().toISOString()},'resolution=merge-duplicates');
const r=await signAndPost(env,local.actor,local.keyId,local.privatePem,inbox,activity);const ok=r.status>=200&&r.status<300;if(!ok){await db(env,`/rest/v1/federation_deliveries`,'POST',{activity_id:(await db(env,`/rest/v1/federated_activities?uri=eq.${enc(id)}&select=id`))?.[0]?.id,target_inbox:inbox,instance_domain:new URL(inbox).hostname,status:'retry',attempt_count:1,next_attempt_at:new Date(Date.now()+60000).toISOString(),last_status_code:r.status,last_error:(await r.text()).slice(0,500)},'return=minimal');return json({queued:true,delivered:false,status:r.status},202)}
if(type.includes('follow')) await db(env,`/rest/v1/federated_follow_requests?local_user_id=eq.${enc(uid)}&remote_actor_uri=eq.${enc(targetActorUri)}`,'PATCH',{state:type==='follow'?'pending':'removed',activity_uri:id,updated_at:new Date().toISOString()});
else await db(env,`/rest/v1/federated_object_reactions?object_uri=eq.${enc(objectUri)}&user_id=eq.${enc(uid)}&reaction_type=eq.${type.includes('repost')?'repost':'like'}`,'PATCH',{active:!(type==='unlike'||type==='unrepost'),activity_uri:id,updated_at:new Date().toISOString()});
return json({delivered:true,status:r.status,activity_id:id});}
async function retry(env:Env){const rows=await db(env,`/rest/v1/federation_deliveries?status=in.(pending,retry)&next_attempt_at=lte.${enc(new Date().toISOString())}&order=next_attempt_at.asc&limit=25`);for(const d of rows||[]){try{const a=await db(env,`/rest/v1/federated_activities?id=eq.${enc(d.activity_id)}&select=*,local_user_id`);if(!a?.[0])continue;const local=await ensureKey(env,a[0].local_user_id);const r=await signAndPost(env,local.actor,local.keyId,local.privatePem,d.target_inbox,a[0].raw_activity);if(r.ok)await db(env,`/rest/v1/federation_deliveries?id=eq.${enc(d.id)}`,'PATCH',{status:'delivered',delivered_at:new Date().toISOString(),last_status_code:r.status});else await db(env,`/rest/v1/federation_deliveries?id=eq.${enc(d.id)}`,'PATCH',{status:d.attempt_count>=7?'dead':'retry',attempt_count:d.attempt_count+1,next_attempt_at:new Date(Date.now()+Math.min(3600000,60000*Math.pow(2,d.attempt_count))).toISOString(),last_status_code:r.status});}catch(e){console.log('delivery retry failed',e)}}}
export default {async fetch(request:Request,env:Env,ctx:ExecutionContext){const p=new URL(request.url).pathname;if(p==='/v1/federation/action'&&request.method==='POST'){try{return await action(request,env)}catch(e){return json({error:'federation_action_failed',message:e instanceof Error?e.message:'unknown'},502)}}return baseFederation.fetch(request,env,ctx)},async scheduled(_c:ScheduledController,env:Env){await retry(env)}};
