package com.fadcam.tv;

import android.app.Dialog;
import android.content.Intent;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.text.InputType;
import android.view.Gravity;
import android.view.MotionEvent;
import android.view.View;
import android.view.Window;
import android.view.WindowManager;
import android.widget.Button;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.HorizontalScrollView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;
import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;
import com.fadcam.tv.social.SocialPost;
import com.fadcam.tv.social.SocialUser;
import com.fadcam.tv.social.SupabaseSocialRepository;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/** Soft, native social home for TV 49 East. */
public final class ModernSocialActivity extends AppCompatActivity {
    private static final int BG=Color.rgb(248,245,251), CARD=Color.WHITE, TEXT=Color.rgb(38,29,48), MUTED=Color.rgb(117,104,126);
    private static final int PRIMARY=Color.rgb(112,82,226), PRIMARY_DARK=Color.rgb(83,57,181), PINK=Color.rgb(245,113,154), SOFT=Color.rgb(241,235,247);
    private final ExecutorService images=Executors.newFixedThreadPool(3);
    private SupabaseSocialRepository repo; private LinearLayout feed; private TextView title; private TextView account;
    private FrameLayout shell; private View drawerScrim; private LinearLayout drawer; private float downX,downY;
    private Uri pendingMedia; private String pendingMediaType; private Dialog authDialog;
    private static final int PICK_MEDIA=701;

    @Override protected void onCreate(@Nullable Bundle state){super.onCreate(state);try{getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(Color.WHITE);repo=new SupabaseSocialRepository(this);build();restoreAndLoad();}catch(Throwable t){fatal(t);}}
    @Override protected void onResume(){super.onResume();if(repo!=null&&feed!=null)refreshAccountState();}
    @Override protected void onDestroy(){images.shutdownNow();if(authDialog!=null)authDialog.dismiss();super.onDestroy();}

    @Override public boolean dispatchTouchEvent(MotionEvent e){
        if(e.getActionMasked()==MotionEvent.ACTION_DOWN){downX=e.getRawX();downY=e.getRawY();}
        if(e.getActionMasked()==MotionEvent.ACTION_UP){float dx=e.getRawX()-downX,dy=e.getRawY()-downY;if(Math.abs(dx)>Math.abs(dy)*1.35f&&Math.abs(dx)>dp(90)){if(drawer!=null&&drawer.getVisibility()==View.VISIBLE){closeDrawer();return true;}if(dx<0)openTv();else openAi();return true;}}
        return super.dispatchTouchEvent(e);
    }

    private void build(){
        shell=new FrameLayout(this);shell.setBackgroundColor(BG);LinearLayout main=col();main.setPadding(dp(14),dp(8),dp(14),0);
        LinearLayout head=row();head.setGravity(Gravity.CENTER_VERTICAL);TextView menu=icon("☰",v->toggleDrawer());menu.setContentDescription("Open TV 49 East navigation");head.addView(menu,new LinearLayout.LayoutParams(dp(42),dp(48)));
        TextView logo=text("49",22,Color.WHITE,true);logo.setGravity(Gravity.CENTER);logo.setBackground(gradient(PRIMARY,PINK,24));head.addView(logo,new LinearLayout.LayoutParams(dp(46),dp(42)));
        title=text("For You",20,TEXT,true);title.setPadding(dp(10),0,0,0);head.addView(title,new LinearLayout.LayoutParams(0,dp(48),1));
        TextView alerts=icon("♡",v->alerts());head.addView(alerts,new LinearLayout.LayoutParams(dp(40),dp(44)));
        Button post=softButton("＋ Post",PRIMARY,SOFT);post.setOnClickListener(v->compose());head.addView(post,new LinearLayout.LayoutParams(dp(90),dp(40)));
        account=softButton("Sign in",PRIMARY,Color.WHITE);account.setOnClickListener(v->accountAction());head.addView(account,new LinearLayout.LayoutParams(dp(82),dp(40)));main.addView(head);
        EditText search=new EditText(this);styleInput(search,"Search creators, posts, football…",false);search.setSingleLine(true);search.setOnEditorActionListener((v,a,e)->{search(v.getText().toString());return true;});main.addView(search,new LinearLayout.LayoutParams(-1,dp(48)));
        main.addView(chips());ScrollView body=new ScrollView(this);body.setFillViewport(true);feed=col();feed.setPadding(0,dp(6),0,dp(96));body.addView(feed,new ScrollView.LayoutParams(-1,-2));main.addView(body,new LinearLayout.LayoutParams(-1,0,1));main.addView(bottom());shell.addView(main,new FrameLayout.LayoutParams(-1,-1));
        Button fab=softButton("＋",Color.WHITE,PINK);fab.setTextSize(25);fab.setOnClickListener(v->compose());FrameLayout.LayoutParams fp=new FrameLayout.LayoutParams(dp(58),dp(58),Gravity.RIGHT|Gravity.BOTTOM);fp.setMargins(0,0,dp(18),dp(76));shell.addView(fab,fp);buildDrawer();setContentView(shell);
    }

    private void restoreAndLoad(){if(!repo.isConfigured()){showBackendUnavailable();return;}if(repo.currentRefreshToken()!=null){repo.restoreSession(r->runOnUiThread(()->{refreshAccountState();loadFeed();}));}else{refreshAccountState();loadFeed();}}
    private void refreshAccountState(){if(account==null)return;if(repo.isSignedIn()){repo.loadProfile(r->runOnUiThread(()->{String label="You";if(r.getValue()!=null)label=initial(r.getValue());account.setText(label);account.setTextColor(Color.WHITE);account.setBackground(round(PRIMARY,22));}));}else{account.setText("Sign in");account.setTextColor(PRIMARY);account.setBackground(round(Color.WHITE,22));}}

    private void buildDrawer(){
        drawerScrim=new View(this);drawerScrim.setBackgroundColor(Color.argb(90,40,24,52));drawerScrim.setVisibility(View.GONE);drawerScrim.setOnClickListener(v->closeDrawer());shell.addView(drawerScrim,new FrameLayout.LayoutParams(-1,-1));
        drawer=col();drawer.setPadding(dp(20),dp(28),dp(20),dp(20));drawer.setBackground(round(Color.WHITE,28));FrameLayout.LayoutParams p=new FrameLayout.LayoutParams(dp(310),-1,Gravity.LEFT);p.setMargins(dp(8),dp(8),dp(8),dp(8));shell.addView(drawer,p);drawer.setVisibility(View.GONE);
        drawer.addView(text("TV 49 EAST",13,PRIMARY,true),new LinearLayout.LayoutParams(-1,dp(28)));drawer.addView(text("Explore",27,TEXT,true),new LinearLayout.LayoutParams(-1,dp(48)));drawer.addView(text("Everything stays close: social, TV, FadCam and more.",13,MUTED,false));
        addDrawerItem("⌂","For You",()->{closeDrawer();title.setText("For You");loadFeed();});addDrawerItem("▣","Live TV",()->{closeDrawer();openTv();});addDrawerItem("◉","FadCam Local Broadcast",()->{closeDrawer();open(FadCamLocalReceiverActivity.class);});addDrawerItem("⚽","Live Scores / Fixtures",()->{closeDrawer();open(FootballActivity.class);});addDrawerItem("▣","Wallet / PayPal",()->{closeDrawer();open(WalletActivity.class);});addDrawerItem("✦","TV 49 East AI",()->{closeDrawer();openAi();});addDrawerItem("♙","My account",()->{closeDrawer();accountAction();});
        TextView hint=text("Tip: swipe left for Live TV or right for AI.",12,MUTED,false);hint.setPadding(0,dp(20),0,0);drawer.addView(hint);
    }
    private void addDrawerItem(String icon,String label,Runnable action){Button b=softButton(icon+"   "+label,TEXT,SOFT);b.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);b.setTextSize(14);b.setOnClickListener(v->action.run());LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(52));p.setMargins(0,dp(5),0,dp(5));drawer.addView(b,p);}
    private void toggleDrawer(){if(drawer.getVisibility()==View.VISIBLE)closeDrawer();else openDrawer();}private void openDrawer(){drawerScrim.setVisibility(View.VISIBLE);drawer.setVisibility(View.VISIBLE);drawerScrim.bringToFront();drawer.bringToFront();}private void closeDrawer(){drawer.setVisibility(View.GONE);drawerScrim.setVisibility(View.GONE);}

    private View chips(){HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);LinearLayout r=row();String[] names={"For You","Following","On TV","Clips","People","Football","Music","Live"};for(String n:names){boolean selected="For You".equals(n);TextView c=text(n,13,selected?Color.WHITE:MUTED,selected);c.setGravity(Gravity.CENTER);c.setPadding(dp(18),0,dp(18),0);c.setBackground(selected?gradient(PRIMARY,PINK,24):round(Color.WHITE,24));final String x=n;c.setOnClickListener(v->{title.setText(x);if("On TV".equals(x)||"Live".equals(x))openTv();else if("Clips".equals(x))reels();else if("People".equals(x))toast("People discovery is coming next");else loadFeed();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,dp(40));p.setMargins(0,dp(5),dp(8),dp(5));r.addView(c,p);}hs.addView(r,new HorizontalScrollView.LayoutParams(-2,dp(50)));return hs;}

    private View bottom(){LinearLayout n=row();n.setGravity(Gravity.CENTER);n.setPadding(dp(6),dp(5),dp(6),dp(5));n.setBackgroundColor(Color.WHITE);String[][] a={{"⌂","For You"},{"♧","Meet Up"},{"▣","Live TV"},{"◯","Chats"},{"♙","Profile"}};for(String[]x:a){LinearLayout cell=col();cell.setGravity(Gravity.CENTER);TextView i=text(x[0],21,"For You".equals(x[1])?PRIMARY:MUTED,true);i.setGravity(Gravity.CENTER);TextView l=text(x[1],10,"For You".equals(x[1])?PRIMARY:MUTED,"For You".equals(x[1]));l.setGravity(Gravity.CENTER);cell.addView(i,new LinearLayout.LayoutParams(-1,dp(27)));cell.addView(l,new LinearLayout.LayoutParams(-1,dp(18)));final String d=x[1];cell.setOnClickListener(v->navigate(d));n.addView(cell,new LinearLayout.LayoutParams(0,dp(54),1));}return n;}

    private void loadFeed(){if(feed==null)return;feed.removeAllViews();if(!repo.isSignedIn()){welcomeCard();return;}loading();repo.loadFeed(30,r->runOnUiThread(()->{if(r.getError()!=null){feed.removeAllViews();errorCard("We couldn't refresh your feed.",r.getError().getMessage());return;}feed.removeAllViews();hero();List<SocialPost> p=r.getValue();if(p==null||p.isEmpty()){empty("Your feed is ready for your first post.\nFollow people, share a moment, or start a conversation.");return;}for(SocialPost x:p)addPost(x);}));}
    private void welcomeCard(){feed.removeAllViews();LinearLayout card=card();card.setPadding(dp(22),dp(22),dp(22),dp(22));card.addView(text("TV 49 EAST SOCIAL",12,PRIMARY,true));card.addView(text("A softer place to share your moment.",25,TEXT,true));card.addView(text("Create your free account, follow creators, post photos or videos, reply, repost and keep up with TV 49 East.",14,MUTED,false));LinearLayout actions=row();Button sign=softButton("Sign in",Color.WHITE,PRIMARY);sign.setOnClickListener(v->showAuth(false));actions.addView(sign,new LinearLayout.LayoutParams(0,dp(46),1));Button join=softButton("Create account",PRIMARY,SOFT);join.setOnClickListener(v->showAuth(true));LinearLayout.LayoutParams jp=new LinearLayout.LayoutParams(0,dp(46),1);jp.leftMargin=dp(8);actions.addView(join,jp);card.addView(actions);addBlock(card);}
    private void hero(){LinearLayout h=card();h.setPadding(dp(20),dp(18),dp(20),dp(18));h.setBackground(gradient(PRIMARY_DARK,PRIMARY,28));h.addView(text("TV 49 EAST SOCIAL",11,Color.rgb(231,220,255),true));h.addView(text("Your people. Your TV. Your moment.",24,Color.WHITE,true));h.addView(text("Creators • football • live TV • community",13,Color.rgb(239,232,248),false));LinearLayout a=row();a.setPadding(0,dp(12),0,0);Button live=softButton("● Live TV",Color.WHITE,Color.argb(55,255,255,255));live.setOnClickListener(v->openTv());a.addView(live,new LinearLayout.LayoutParams(dp(112),dp(42)));Button clip=softButton("▶ Clips",Color.WHITE,Color.argb(55,255,255,255));clip.setOnClickListener(v->reels());LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(dp(100),dp(42));cp.leftMargin=dp(8);a.addView(clip,cp);h.addView(a);addBlock(h);}

    private void addPost(SocialPost p){LinearLayout card=card();card.setPadding(dp(16),dp(14),dp(16),dp(8));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,dp(6),0,dp(6));feed.addView(card,cp);SocialUser u=p.getAuthor();LinearLayout h=row();h.setGravity(Gravity.CENTER_VERTICAL);TextView av=text(initial(u),15,Color.WHITE,true);av.setGravity(Gravity.CENTER);av.setBackground(gradient(PRIMARY,PINK,50));h.addView(av,new LinearLayout.LayoutParams(dp(44),dp(44)));LinearLayout who=col();who.setPadding(dp(10),0,0,0);who.addView(text(clean(u==null?null:u.getDisplayName(),"TV 49 East creator"),15,TEXT,true));who.addView(text("@"+clean(u==null?null:u.getUsername(),"creator")+"  ·  "+relative(p.getCreatedAt()),12,MUTED,false));h.addView(who,new LinearLayout.LayoutParams(0,dp(48),1));h.addView(text("•••",15,MUTED,false),new LinearLayout.LayoutParams(dp(34),dp(36)));card.addView(h);String body=clean(p.getBody(),"");if(!body.isEmpty())card.addView(text(body,16,TEXT,false));String mediaUrl=p.mediaUrlForJava();if(mediaUrl!=null&&!mediaUrl.trim().isEmpty()){ImageView image=new ImageView(this);image.setScaleType(ImageView.ScaleType.CENTER_CROP);image.setBackground(round(SOFT,20));LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(-1,dp(300));ip.setMargins(0,dp(10),0,dp(8));card.addView(image,ip);loadImage(image,mediaUrl);}LinearLayout actions=row();actions.addView(action("♡  "+p.getLikeCount(),v->guardedLike(p)),weight());actions.addView(action("↗  "+p.getRepostCount(),v->guardedRepost(p)),weight());actions.addView(action("○  "+p.getReplyCount(),v->reply(p)),weight());actions.addView(action("⌁",v->share(p)),weight());card.addView(actions);}
    private void guardedLike(SocialPost p){if(!requireAuth())return;repo.likePost(p.getId(),true,feedback("Liked"));}private void guardedRepost(SocialPost p){if(!requireAuth())return;repo.repostPost(p.getId(),true,feedback("Reposted"));}

    private void compose(){if(!requireAuth())return;pendingMedia=null;pendingMediaType=null;final Dialog d=new Dialog(this);d.requestWindowFeature(Window.FEATURE_NO_TITLE);LinearLayout b=sheet();b.addView(text("Create a post",22,TEXT,true));b.addView(text("Share a thought, photo or video with your community.",13,MUTED,false));EditText body=new EditText(this);styleInput(body,"What's happening?",false);body.setMinLines(4);body.setGravity(Gravity.TOP);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(118));bp.setMargins(0,dp(14),0,dp(10));b.addView(body,bp);TextView attachment=text("＋  Add photo or video",14,PRIMARY,true);attachment.setGravity(Gravity.CENTER_VERTICAL);attachment.setPadding(dp(14),0,dp(14),0);attachment.setBackground(round(SOFT,18));attachment.setOnClickListener(v->pickMedia());b.addView(attachment,new LinearLayout.LayoutParams(-1,dp(48)));LinearLayout actions=row();Button cancel=softButton("Cancel",MUTED,SOFT);cancel.setOnClickListener(v->d.dismiss());Button publish=softButton("Post",Color.WHITE,PRIMARY);publish.setOnClickListener(v->publishPost(d,body.getText().toString()));actions.addView(cancel,new LinearLayout.LayoutParams(0,dp(48),1));LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(0,dp(48),1);pp.leftMargin=dp(8);actions.addView(publish,pp);LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,dp(52));ap.topMargin=dp(12);b.addView(actions,ap);d.setContentView(b);showBottomSheet(d);}
    private void publishPost(Dialog d,String body){String text=body.trim();if(text.isEmpty()&&pendingMedia==null){toast("Write something or attach media");return;}if(pendingMedia!=null){toast("Uploading media…");String kind="image".equals(pendingMediaType)?"post-image":"post-video";repo.uploadMedia(pendingMedia,kind,r->{if(r.getError()!=null){toast(r.getError().getMessage());return;}repo.createPost(text,r.getValue(),pendingMediaType,postResult(d));});}else repo.createPost(text,postResult(d));}
    private SupabaseSocialRepository.ResultCallback<SocialPost?> postResult(Dialog d){return r->{if(r.getError()!=null){toast(r.getError().getMessage());return;}runOnUiThread(()->{d.dismiss();toast("Posted");loadFeed();});};}

    private void reply(SocialPost p){if(!requireAuth())return;final Dialog d=new Dialog(this);d.requestWindowFeature(Window.FEATURE_NO_TITLE);LinearLayout b=sheet();b.addView(text("Reply",21,TEXT,true));b.addView(text("Join the conversation.",13,MUTED,false));EditText in=new EditText(this);styleInput(in,"Write a reply…",false);in.setMinLines(3);LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(-1,dp(100));ip.topMargin=dp(14);b.addView(in,ip);LinearLayout a=row();Button cancel=softButton("Cancel",MUTED,SOFT);cancel.setOnClickListener(v->d.dismiss());Button send=softButton("Reply",Color.WHITE,PRIMARY);send.setOnClickListener(v->repo.replyToPost(p.getId(),in.getText().toString(),r->{if(r.getError()!=null)toast(r.getError().getMessage());else{d.dismiss();toast("Reply sent");}}));a.addView(cancel,new LinearLayout.LayoutParams(0,dp(48),1));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(0,dp(48),1);sp.leftMargin=dp(8);a.addView(send,sp);LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,dp(52));ap.topMargin=dp(12);b.addView(a,ap);d.setContentView(b);showBottomSheet(d);}

    private boolean requireAuth(){if(repo.isSignedIn())return true;showAuth(false);return false;}
    private void accountAction(){if(repo.isSignedIn())accountMenu();else showAuth(false);}
    private void showAuth(boolean startSignup){if(authDialog!=null&&authDialog.isShowing())authDialog.dismiss();final Dialog d=new Dialog(this);authDialog=d;d.requestWindowFeature(Window.FEATURE_NO_TITLE);LinearLayout root=sheet();TextView titleView=text(startSignup?"Create your account":"Welcome back",25,TEXT,true);root.addView(titleView);root.addView(text(startSignup?"Join TV 49 East in under a minute.":"Sign in to keep posting and following people.",13,MUTED,false));LinearLayout tabs=row();Button signTab=softButton("Sign in",startSignup?MUTED:Color.WHITE,startSignup?SOFT:PRIMARY);Button upTab=softButton("Create account",startSignup?Color.WHITE:MUTED,startSignup?PRIMARY:SOFT);tabs.addView(signTab,new LinearLayout.LayoutParams(0,dp(44),1));LinearLayout.LayoutParams up=new LinearLayout.LayoutParams(0,dp(44),1);up.leftMargin=dp(8);tabs.addView(upTab,up);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(-1,dp(50));tp.topMargin=dp(16);root.addView(tabs,tp);LinearLayout fields=col();root.addView(fields,new LinearLayout.LayoutParams(-1,-2));renderAuthFields(fields,d,startSignup);signTab.setOnClickListener(v->{d.dismiss();showAuth(false);});upTab.setOnClickListener(v->{d.dismiss();showAuth(true);});d.setContentView(root);showBottomSheet(d);}
    private void renderAuthFields(LinearLayout fields,Dialog d,boolean signup){fields.removeAllViews();EditText name=null,user=null;if(signup){name=new EditText(this);styleInput(name,"Display name",false);fields.addView(name,new LinearLayout.LayoutParams(-1,dp(48)));user=new EditText(this);styleInput(user,"Username",false);LinearLayout.LayoutParams up=new LinearLayout.LayoutParams(-1,dp(48));up.topMargin=dp(8);fields.addView(user,up);}EditText email=new EditText(this);styleInput(email,"Email",false);LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(-1,dp(48));ep.topMargin=dp(8);fields.addView(email,ep);EditText pass=new EditText(this);styleInput(pass,"Password",true);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,dp(48));pp.topMargin=dp(8);fields.addView(pass,pp);TextView forgot=text("Forgot password?",13,PRIMARY,true);forgot.setPadding(0,dp(12),0,dp(4));forgot.setOnClickListener(v->resetPassword(email.getText().toString()));fields.addView(forgot);Button action=softButton(signup?"Create account":"Sign in",Color.WHITE,PRIMARY);action.setOnClickListener(v->{if(signup){repo.signUp(email.getText().toString(),pass.getText().toString(),user.getText().toString(),name.getText().toString(),r->{if(r.getError()!=null){toast(r.getError().getMessage());return;}if(r.getValue()!=null&&r.getValue().getAccessToken().isBlank()){d.dismiss();toast("Account created. Check your email to verify it, then sign in.");}else{d.dismiss();toast("Welcome to TV 49 East");loadFeed();}});}else{repo.signIn(email.getText().toString(),pass.getText().toString(),r->{if(r.getError()!=null){toast(r.getError().getMessage());return;}d.dismiss();toast("Welcome back");loadFeed();refreshAccountState();});}});LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,dp(50));ap.topMargin=dp(12);fields.addView(action,ap);TextView note=text("By continuing you agree to use TV 49 East responsibly and respect other people.",11,MUTED,false);note.setPadding(0,dp(12),0,0);fields.addView(note);}
    private void resetPassword(String email){if(email.trim().isEmpty()){toast("Enter your email first");return;}repo.resetPassword(email,r->{if(r.getError()!=null)toast(r.getError().getMessage());else toast("Password reset instructions sent");});}
    private void accountMenu(){final Dialog d=new Dialog(this);d.requestWindowFeature(Window.FEATURE_NO_TITLE);LinearLayout b=sheet();b.addView(text("Your account",22,TEXT,true));Button profile=softButton("♙  Open profile",TEXT,SOFT);profile.setOnClickListener(v->{d.dismiss();profile();});b.addView(profile,new LinearLayout.LayoutParams(-1,dp(50)));Button signout=softButton("Sign out",Color.rgb(196,71,103),Color.rgb(253,237,242));signout.setOnClickListener(v->{repo.signOut();d.dismiss();refreshAccountState();loadFeed();toast("Signed out");});LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,dp(50));sp.topMargin=dp(8);b.addView(signout,sp);d.setContentView(b);showBottomSheet(d);}

    private void alerts(){if(!requireAuth())return;repo.loadNotifications(30,r->runOnUiThread(()->{String message=r.getError()!=null?"Notifications are unavailable right now.":clean(r.getValue(),"No notifications yet.");new androidx.appcompat.app.AlertDialog.Builder(this).setTitle("Notifications").setMessage(message).setPositiveButton("Done",null).show();}));}
    private void search(String q){if(q==null||q.trim().isEmpty())return;if(!requireAuth())return;loading();repo.searchPosts(q.trim(),30,r->runOnUiThread(()->{feed.removeAllViews();title.setText("Search");if(r.getError()!=null)errorCard("Search couldn't load",r.getError().getMessage());else if(r.getValue()==null||r.getValue().isEmpty())empty("No matching posts yet.");else for(SocialPost p:r.getValue())addPost(p);}));}
    private void navigate(String d){if("Live TV".equals(d)){openTv();return;}if("Profile".equals(d)){if(requireAuth())profile();return;}if("Meet Up".equals(d)){if(!requireAuth())return;title.setText("Meet Up");loading();repo.loadTrending(20,r->runOnUiThread(()->{feed.removeAllViews();if(r.getError()!=null)errorCard("Meet Up couldn't load",r.getError().getMessage());else if(r.getValue()!=null)for(SocialPost p:r.getValue())addPost(p);else empty("No recommendations yet.");}));return;}if("Chats".equals(d)){if(!requireAuth())return;toast("Chats are connected to the conversation backend; the full inbox is the next native surface.");return;}title.setText("For You");loadFeed();}

    private void pickMedia(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"image/*","video/*"});i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,PICK_MEDIA);}
    @Override protected void onActivityResult(int requestCode,int resultCode,@Nullable Intent data){super.onActivityResult(requestCode,resultCode,data);if(requestCode==PICK_MEDIA&&resultCode==RESULT_OK&&data!=null&&data.getData()!=null){pendingMedia=data.getData();String mime=getContentResolver().getType(pendingMedia);pendingMediaType=mime!=null&&mime.startsWith("video/")?"video":"image";toast(pendingMediaType.equals("video")?"Video attached":"Photo attached");}}

    private void openTv(){startActivity(new Intent(this,MainActivity.class));overridePendingTransition(android.R.anim.slide_in_left,android.R.anim.slide_out_right);finish();}private void openAi(){open(AiAssistantActivity.class);}private void open(Class<?> c){startActivity(new Intent(this,c));overridePendingTransition(android.R.anim.slide_in_left,android.R.anim.slide_out_right);}private void reels(){startActivity(new Intent(this,ReelsActivity.class));}private void profile(){startActivity(new Intent(this,ProfessionalProfileActivity.class));}private void share(SocialPost p){Intent s=new Intent(Intent.ACTION_SEND);s.setType("text/plain");s.putExtra(Intent.EXTRA_TEXT,clean(p.getBody(),"TV 49 East post"));startActivity(Intent.createChooser(s,"Share post"));}

    private LinearLayout sheet(){LinearLayout b=col();b.setPadding(dp(22),dp(20),dp(22),dp(20));b.setBackground(round(Color.WHITE,28));return b;}
    private void showBottomSheet(Dialog d){d.show();Window w=d.getWindow();if(w!=null){w.setBackgroundDrawable(round(Color.TRANSPARENT,28));WindowManager.LayoutParams lp=w.getAttributes();lp.width=(int)(getResources().getDisplayMetrics().widthPixels*0.96f);lp.gravity=Gravity.BOTTOM;w.setAttributes(lp);w.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);}}
    private void styleInput(EditText e,String hint,boolean password){e.setHint(hint);e.setTextColor(TEXT);e.setHintTextColor(Color.rgb(150,139,158));e.setTextSize(14);e.setPadding(dp(16),0,dp(16),0);e.setBackground(round(SOFT,18));if(password)e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);}
    private Button softButton(String s,int fg,int bg){Button b=new Button(this);b.setText(s);b.setTextColor(fg);b.setTextSize(13);b.setAllCaps(false);b.setMinHeight(0);b.setMinWidth(0);b.setPadding(dp(10),0,dp(10),0);b.setBackground(round(bg,22));return b;}
    private Button action(String s,View.OnClickListener l){Button b=softButton(s,MUTED,Color.TRANSPARENT);b.setTextSize(12);b.setOnClickListener(l);return b;}private LinearLayout.LayoutParams weight(){return new LinearLayout.LayoutParams(0,dp(40),1);}
    private TextView icon(String s,View.OnClickListener l){TextView t=text(s,22,TEXT,true);t.setGravity(Gravity.CENTER);t.setOnClickListener(l);return t;}
    private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);return l;}private LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
    private TextView text(String s,float size,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setTypeface(Typeface.DEFAULT,bold?Typeface.BOLD:Typeface.NORMAL);return t;}
    private GradientDrawable round(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}private GradientDrawable gradient(int a,int b,int radius){GradientDrawable d=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{a,b});d.setCornerRadius(dp(radius));return d;}
    private LinearLayout card(){LinearLayout l=col();l.setBackground(round(CARD,24));l.setElevation(dp(1));return l;}
    private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}private String clean(String s,String f){return s==null||s.trim().isEmpty()?f:s.trim();}private String initial(SocialUser u){String s=clean(u==null?null:u.getDisplayName(),"T");return s.substring(0,1).toUpperCase();}
    private void addBlock(View v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(6),0,dp(8));feed.addView(v,p);}private void empty(String s){TextView t=text(s,14,MUTED,false);t.setGravity(Gravity.CENTER);t.setPadding(dp(24),dp(35),dp(24),dp(35));addBlock(t);}private void loading(){if(feed==null)return;feed.removeAllViews();ProgressBar p=new ProgressBar(this);LinearLayout wrap=col();wrap.setGravity(Gravity.CENTER);wrap.setPadding(0,dp(45),0,dp(45));wrap.addView(p);feed.addView(wrap,new LinearLayout.LayoutParams(-1,-2));}
    private void errorCard(String titleText,String detail){LinearLayout c=card();c.setPadding(dp(20),dp(18),dp(20),dp(18));c.addView(text(titleText,18,TEXT,true));c.addView(text(clean(detail,"Please try again."),13,MUTED,false));Button retry=softButton("Try again",Color.WHITE,PRIMARY);retry.setOnClickListener(v->loadFeed());LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,dp(46));rp.topMargin=dp(12);c.addView(retry,rp);addBlock(c);}
    private void showBackendUnavailable(){feed.removeAllViews();LinearLayout c=card();c.setPadding(dp(20),dp(20),dp(20),dp(20));c.addView(text("Social is not configured",20,TEXT,true));c.addView(text("The app build does not contain a valid Supabase endpoint. Nothing will crash; this screen will stay usable until the backend is configured.",13,MUTED,false));addBlock(c);}
    private void toast(String s){runOnUiThread(()->Toast.makeText(this,clean(s,"Done"),Toast.LENGTH_SHORT).show());}private SupabaseSocialRepository.ResultCallback<Boolean> feedback(String ok){return r->{if(r.getError()!=null)toast(r.getError().getMessage());else toast(ok);};}
    private String relative(String s){if(s==null||s.isEmpty())return "now";try{long t=java.time.Instant.parse(s).toEpochMilli();long m=Math.max(0,(System.currentTimeMillis()-t)/60000);if(m<1)return "now";if(m<60)return m+"m";if(m<1440)return m/60+"h";return m/1440+"d";}catch(Throwable ignored){return "now";}}
    private void fatal(Throwable t){TextView v=text("TV 49 East Social couldn't open.\n\n"+clean(t.getMessage(),t.getClass().getSimpleName()),15,TEXT,false);v.setGravity(Gravity.CENTER);v.setPadding(dp(24),dp(24),dp(24),dp(24));v.setBackgroundColor(BG);setContentView(v);}
    private void loadImage(ImageView v,String url){images.execute(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setConnectTimeout(8000);c.setReadTimeout(12000);c.connect();InputStream in=c.getInputStream();android.graphics.Bitmap b=android.graphics.BitmapFactory.decodeStream(in);in.close();c.disconnect();if(b!=null)runOnUiThread(()->v.setImageBitmap(b));}catch(Throwable ignored){}});}
}
