'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';

type Post={id:string;body:string;media_url:string|null;created_at:string;like_count:number;reply_count:number;repost_count:number;author?:{username:string;display_name:string;avatar_url:string|null}};
export default function Home(){const[posts,setPosts]=useState<Post[]>([]);const[body,setBody]=useState('');const[user,setUser]=useState<any>(null);const[status,setStatus]=useState('');
 useEffect(()=>{load();supabase.auth.getUser().then(({data})=>setUser(data.user));const{data}=supabase.auth.onAuthStateChange((_,s)=>setUser(s?.user??null));return()=>data.subscription.unsubscribe()},[]);
 async function load(){const{data}=await supabase.from('posts').select('id,body,media_url,created_at,like_count,reply_count,repost_count,profiles:author_id(username,display_name,avatar_url)').order('created_at',{ascending:false}).limit(30);setPosts((data||[]) as any)}
 async function post(){if(!user){setStatus('Sign in first.');return}if(!body.trim())return;const{error}=await supabase.from('posts').insert({author_id:user.id,body:body.trim()});if(error)setStatus(error.message);else{setBody('');setStatus('Posted');load()}}
 async function like(p:Post){if(!user){setStatus('Sign in first.');return}const{data}=await supabase.from('post_likes').select('post_id').eq('post_id',p.id).eq('user_id',user.id).maybeSingle();if(data)await supabase.from('post_likes').delete().eq('post_id',p.id).eq('user_id',user.id);else await supabase.from('post_likes').insert({post_id:p.id,user_id:user.id});load()}
 return <main className="feed"><section className="hero"><span className="eyebrow">TESTAGRAM • TV 49 EAST</span><h1>Share the moment.</h1><p>A modern home for creators, football, live TV, conversations and community.</p><div className="hero-actions"><a className="btn primary" href="/explore">Explore</a><a className="btn ghost" href="/media">Create with camera</a></div></section><section className="composer card"><div className="avatar">49</div><div className="composer-body"><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder={user?'What is happening?':'Sign in to post on Testagram…'} maxLength={5000}/><div className="composer-row"><span>{status}</span><button className="btn primary" onClick={post}>Post</button></div></div></section><div className="section-head"><h2>For You</h2><button onClick={load} className="text-btn">Refresh</button></div><section className="post-list">{posts.length===0?<div className="card empty">No posts yet. Be the first voice in the community.</div>:posts.map(p=><article className="card post" key={p.id}><div className="post-head"><div className="avatar small">{(p.author?.display_name||p.author?.username||'49').slice(0,2).toUpperCase()}</div><div><b>{p.author?.display_name||'Testagram creator'}</b><div className="muted">@{p.author?.username||'creator'} · {new Date(p.created_at).toLocaleString()}</div></div></div><p>{p.body}</p>{p.media_url&&<img src={p.media_url} alt="Post media"/>}<div className="post-actions"><button onClick={()=>like(p)}>♡ {p.like_count}</button><button>◌ {p.reply_count}</button><button>↻ {p.repost_count}</button><button>🔖 Save</button></div></article>)}</section></main>}
